# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#123F78", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("slug", models.SlugField(max_length=420, unique=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="events/%Y/"),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/posters/%Y/"
                    ),
                ),
                ("short_description", models.TextField(blank=True, max_length=400)),
                ("description", tinymce.models.HTMLField(blank=True)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=300)),
                ("address", models.TextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City, Country", max_length=300
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("organizer", models.CharField(blank=True, max_length=300)),
                ("guest_artists", models.TextField(blank=True)),
                ("guest_speakers", models.TextField(blank=True)),
                ("registration_url", models.URLField(blank=True)),
                ("ticket_info", models.TextField(blank=True)),
                (
                    "ticket_price",
                    models.CharField(
                        blank=True, help_text="e.g. Free, 2000 RWF", max_length=100
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("youtube_livestream_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=300)),
                ("seo_description", models.TextField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.eventtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("youtube_url", models.URLField()),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="streams/"),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("show_on_homepage", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="streams",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Stream",
                "verbose_name_plural": "Live Streams",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_date"], name="events_even_status_dfba18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_even_slug_30eb0f_idx"),
        ),
    ]
