# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sponsors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("admin", "Website Administrator"),
                            ("editor", "Editor"),
                            ("author", "Author"),
                            ("music_manager", "Music Manager"),
                            ("events_manager", "Events Manager"),
                            ("gallery_manager", "Gallery Manager"),
                            ("sponsor_manager", "Sponsor Manager"),
                            ("ad_manager", "Advertisement Manager"),
                            ("sponsor", "Sponsor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=30,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True)),
                ("is_choir_member", models.BooleanField(default=False)),
                (
                    "voice_part",
                    models.CharField(
                        blank=True,
                        help_text="Soprano, Alto, Tenor, Bass, etc.",
                        max_length=50,
                    ),
                ),
                ("date_joined_choir", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsor_application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="sponsors.sponsorapplication",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
