# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("person_name", models.CharField(max_length=200)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonies/photos/"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="testimonies/"),
                ),
                ("testimony_text", tinymce.models.HTMLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("testimony_date", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_public_submission", models.BooleanField(default=False)),
                ("submitter_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimony",
                "verbose_name_plural": "Testimonies",
                "ordering": ["-testimony_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvangelizationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="evangelization/%Y/"
                    ),
                ),
                ("content", tinymce.models.HTMLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "participants_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evangelization Report",
                "verbose_name_plural": "Evangelization Reports",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
    ]
