# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="albums/"),
                ),
                ("description", tinymce.models.HTMLField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("spotify_url", models.URLField(blank=True)),
                ("apple_music_url", models.URLField(blank=True)),
                ("boomplay_url", models.URLField(blank=True)),
                ("youtube_playlist_url", models.URLField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=300)),
                ("seo_description", models.TextField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["-release_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                ("track_number", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("lyrics", tinymce.models.HTMLField(blank=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="songs/audio/"),
                ),
                ("youtube_url", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                ("apple_music_url", models.URLField(blank=True)),
                ("boomplay_url", models.URLField(blank=True)),
                ("composer", models.CharField(blank=True, max_length=300)),
                ("lead_singer", models.CharField(blank=True, max_length=300)),
                ("producer", models.CharField(blank=True, max_length=300)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.DurationField(blank=True, help_text="HH:MM:SS", null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs",
                        to="music.album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
                "ordering": ["album", "track_number", "title"],
            },
        ),
    ]
