# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="committee/"),
                ),
                ("short_bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Committee Member",
                "verbose_name_plural": "Committee Members",
                "ordering": ["order", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=500)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Heroicon name", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="partners/"),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("ministry", "Ministry Partner"),
                            ("media", "Media Partner"),
                            ("sponsor", "Sponsor Partner"),
                            ("educational", "Educational Partner"),
                            ("other", "Other"),
                        ],
                        default="ministry",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Jehovah Jireh Choir – ULK", max_length=200
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "logo_white",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("phone_2", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                (
                    "city",
                    models.CharField(blank=True, default="Kigali", max_length=100),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="Rwanda", max_length=100),
                ),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("twitter", models.URLField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                ("copyright_text", models.CharField(blank=True, max_length=300)),
                (
                    "sponsor_cta_text",
                    models.CharField(
                        blank=True, default="Become a Sponsor", max_length=200
                    ),
                ),
                (
                    "sponsor_cta_url",
                    models.CharField(
                        blank=True,
                        default="/sponsors/become-a-sponsor/",
                        max_length=200,
                    ),
                ),
                ("default_seo_description", models.TextField(blank=True)),
                (
                    "default_seo_image",
                    models.ImageField(blank=True, null=True, upload_to="site/seo/"),
                ),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                (
                    "google_maps_embed",
                    models.TextField(blank=True, help_text="Google Maps embed HTML"),
                ),
                ("working_hours", models.TextField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SliderSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("heading", models.CharField(blank=True, max_length=300)),
                (
                    "highlighted_text",
                    models.CharField(
                        blank=True, help_text="Text shown in gold color", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("desktop_image", models.ImageField(upload_to="slider/")),
                (
                    "mobile_image",
                    models.ImageField(blank=True, null=True, upload_to="slider/"),
                ),
                ("button_1_text", models.CharField(blank=True, max_length=100)),
                ("button_1_url", models.CharField(blank=True, max_length=500)),
                ("button_2_text", models.CharField(blank=True, max_length=100)),
                ("button_2_url", models.CharField(blank=True, max_length=500)),
                (
                    "text_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "overlay_opacity",
                    models.FloatField(default=0.55, help_text="0.0 to 1.0"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("schedule_start", models.DateTimeField(blank=True, null=True)),
                ("schedule_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slider Slide",
                "verbose_name_plural": "Slider Slides",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("file", models.FileField(upload_to="library/%Y/%m/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=300)),
                ("caption", models.TextField(blank=True)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=500)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Library",
                "ordering": ["-created_at"],
            },
        ),
    ]
