# Generated by Django 5.0.9 on 2026-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliderslide",
            name="desktop_image",
            field=models.ImageField(blank=True, null=True, upload_to="slider/"),
        ),
    ]
