# Generated by Django 5.0.9 on 2026-08-09 10:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_sliderslide_desktop_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about",
            field=tinymce.models.HTMLField(
                blank=True, help_text="About the choir — shown on About page"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission",
            field=tinymce.models.HTMLField(blank=True, help_text="Mission statement"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision",
            field=tinymce.models.HTMLField(blank=True, help_text="Vision statement"),
        ),
    ]
