# Generated by Django 5.1.6 on 2026-08-14 08:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_sitesettings_about_sitesettings_mission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("eyebrow", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True, max_length=600)),
                ("body", tinymce.models.HTMLField(blank=True)),
                ("closing_statement", models.CharField(blank=True, max_length=300)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Content Page",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MinistryArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("summary", models.TextField(max_length=500)),
                ("body", tinymce.models.HTMLField(blank=True)),
                ("link_url", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("show_on_homepage", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("value", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=120)),
                ("detail", models.CharField(blank=True, max_length=250)),
                ("order", models.PositiveIntegerField(default=0)),
                ("show_on_homepage", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="TimelineMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "year"],
            },
        ),
    ]
