# Generated by Django 5.1.6 on 2026-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_contentpage_ministryarea_sitestatistic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="content/"),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="featured_image_alt",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
