# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=300)),
                ("contact_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("ad_image", models.ImageField(upload_to="ads/%Y/")),
                ("destination_url", models.URLField()),
                ("alt_text", models.CharField(blank=True, max_length=300)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ad Campaign",
                "verbose_name_plural": "Ad Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                (
                    "impressions_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="0 = unlimited", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Ad Package",
                "verbose_name_plural": "Ad Packages",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="AdPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "recommended_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "recommended_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ad Position",
                "verbose_name_plural": "Ad Positions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_click", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="advertising.adcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Impression",
                "verbose_name_plural": "Ad Impressions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="advertising.adpackage",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="positions",
            field=models.ManyToManyField(blank=True, to="advertising.adposition"),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="advertising.adposition",
            ),
        ),
    ]
