# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(unique=True)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/covers/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_albums",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Album",
                "verbose_name_plural": "Gallery Albums",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/%Y/%m/"
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=300)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="gallery.galleryalbum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Media",
                "verbose_name_plural": "Gallery Media",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
