# Generated by Django 5.0.9 on 2026-08-09 09:07

import django.db.models.deletion
import taggit.managers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#123F78", help_text="Hex color", max_length=7
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=520, unique=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/%Y/%m/"
                    ),
                ),
                ("featured_image_alt", models.CharField(blank=True, max_length=300)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary shown in listings",
                        max_length=500,
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Embedded video URL (YouTube/Vimeo)"
                    ),
                ),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=300)),
                ("seo_description", models.TextField(blank=True, max_length=300)),
                (
                    "seo_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/seo/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="cms.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_date"],
                        name="cms_article_status_41b302_idx",
                    ),
                    models.Index(fields=["slug"], name="cms_article_slug_f1890b_idx"),
                ],
            },
        ),
    ]
